### ISSUE TITLE
Traits morphosyntaxiques des verbes

### ISSUE THREAD

**Issue by VanessaGB** [surfacesyntacticud/SUD_French-Rhapsodie#1]
Bonjour,

En travaillant sur le corpus Rhapsodie, j'ai pu m'apercevoir que certains traits morphosyntaxiques des verbes (Tense, Mood et VerbForm) n'apparaissent pas toujours dans la colonne correspondante. En effet, certaines fois, seuls les traits Number et Person sont renseignés et ce genre de cas est assez fréquent.
En tentant de trouver une régularité, il me semble que c’est en majorité dans les cas où les verbes sont à la deuxième personne voire à la première que les informations morphosyntaxiques sont incomplètes, mais la règle est loin de se vérifier tout le temps pour autant.
Par ailleurs, dans certains autres cas, comme par exemple quand le verbe est au sein d’un idiome, quand il a une relation discourse ou, parfois, lorsqu’il est à l’impératif, qu’il a une relation comp:aux, etc., la colonne des traits morphosyntaxiques reste là entièrement vide.

Souhaitez-vous que nous ajoutions ces traits manquants dans tous ces cas où ils n’apparaissent pas ? Ou bien seulement dans certains des cas que j’ai décrits ?

Si vous souhaitez voir ce que cela donne par vous-mêmes, je joins à ce message les verbes du sous-corpus test que j'ai isolés dans un document.

[verbes_test.txt](https://github.com/surfacesyntacticud/SUD_French-Spoken/files/7025411/verbes_test.txt)

Merci par avance et bonne journée !

**Comment by bguil** [comment]
Les traits des verbes ont été corrigés
